config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create destroy edit update]
  resources :projects, only: %i[new create destroy edit update]
  resources :archives

  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end

  root 'pages#index'
  get 'session' => 'sessions#destroy'

  resources :questions do
    post :start_working, on: :member
    post :completed_working, on: :member
    post :send_to_archive, on: :member
    post :back_to_active, on: :member
    get :back_to_active, on: :member
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy
  belongs_to :project, optional: true
  has_many_attached :question_files, dependent: :destroy

  has_many :users

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
  validates :question_files, size: { less_than: 1.megabytes, message: 'hello' }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :require_authentication
  before_action :set_question!, only: %i[show destroy edit update start_working completed_working send_to_archive back_to_active]
  before_action :fetch_question_responsible, only: %i[new edit]
  before_action :fetch_projects, only: %i[new edit]

  def index
    @questions = Question.includes(:user).where(user_id: current_user).where.not(statuses_id: 4).page(params[:page]).per(10).order(:statuses_id, created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    question = current_user.questions.build question_params
    if question.save
      flash[:check] = 'Заявка создана!'
      redirect_to questions_path
    else
      redirect_to new_question_path
      flash[:times] = "Ошибка, файл слишком большой!"
      # render :new
    end
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:check] = 'Заявка обновлена'
      redirect_to questions_path+'/'+@question.id.to_s
    else
      render :edit
    end
  end

  def destroy
    @question.question_files.purge_later
    @question.destroy
    if @question.destroy
      flash[:times] = 'Ваша заявка была удалена'
      redirect_to archives_path
    end
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.all
  end

  def start_working
    @question.update(statuses_id: 2)
    if @question.update(statuses_id: 2)
      flash[:exclamation] = "Статус заявки изменился на «В работе»"
      redirect_to questions_path+'/'+@question.id.to_s
    end
  end

  def completed_working
    @question.update(statuses_id: 3)
    if @question.update(statuses_id: 3)
      flash[:check] = "Статус заявки изменился на «Готово»"
      redirect_to questions_path+'/'+@question.id.to_s
    end
  end

  def send_to_archive
    @question.update(statuses_id: 4)
    if @question.update(statuses_id: 4)
      flash[:times] = "Заявка перенесена в «Архив»"
      DestroyInArchiveJob.perform_async('bob')
      # DestroyInArchiveJob.deliver_later(wait: 1.second)
      redirect_to questions_path
    end
  end

  def back_to_active
    @question.update(statuses_id: 1)
    if @question.update(statuses_id: 1)
      flash[:check] = "Статус заявки изменился на «Открыта»"
      redirect_to questions_path+'/'+@question.id.to_s
    end
  end


  private

  def question_params
    params.require(:question).permit(:title, :body, :users_id, :statuses_id, :project_id, question_files: [])
  end

  def set_question!
    @question = Question.find params[:id]
  end

  def fetch_question_responsible
    @question_responsibles = User.all
  end

  def fetch_projects
    @collection_projects = Project.all
  end

end

app/views/questions/_animation_empty_messages.html.erb
<div class="aquarium">
  <div class="aquarium__table"></div>
  <div class="aquarium__aquarium">
    <div class="aquarium__water"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
    <div class="aquarium__bubble"></div>
  </div>
  <div class="aquarium__drops">
    <div class="aquarium__drop"></div>
    <div class="aquarium__water-column"></div>
    <div class="aquarium__splash"></div>
    <div class="aquarium__splash"></div>
  </div>
  <div class="aquarium__sponge-box">
    <div class="aquarium__body">
      <div class="aquarium__body-stripe"></div>
      <div class="aquarium__body-hole"></div>
    </div>
    <div class="aquarium__face">
      <div class="aquarium__mouth"></div>
      <div class="aquarium__smile"></div>
    </div>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>

<div class="mt-4 mb-2">
  <%= f.label "Тема:" %>
</div>
<div>
  <%= f.text_field :title, required: true, minlength: 2, placeholder: 'Описание к заявке (кратко)', class: "form-control" %>
</div>

<div class="mt-4 mb-2">
  <%= f.label "Подробное описание:" %>
</div>
<div>
  <%= f.text_area :body, required: true, minlength: 2, class: "form-control" %>
</div>

<%= f.submit "Отправить", class: "w-100 btn btn-lg btn-primary", id: 'submit' %>
<% end %>

app/views/questions/_form_create_answer.html.erb
<%= form_with model: [@question, @answer] do |f| %>

  <div class="mt-4 mb-2">
    <%= f.label "Ответить:" %>
  </div>
  <div>
    <%= f.text_field :body, required: true, minlength: 2, class: "form-control", autocomplete: "off", autofocus: true %>
  </div>

  <%= f.submit (@answer.new_record? ? "Ответить" : "Исправить"), class: "w-100 btn btn-lg btn-primary ml-0", id: 'submit' %>
<% end %>

app/views/questions/_form_create_question.html.erb
<%= form_with model: @question do |f| %>

<div class="mt-4 mb-2">
  <%= f.label "Проект:" %>
</div>
<div>
  <%= f.collection_select :project_id, projects, :id, :project_name %>
</div>

<div class="mt-4 mb-2">
  <%= f.label "Тема:" %>
</div>
<div>
  <%= f.text_field :title, required: true, minlength: 2, placeholder: 'Описание к заявке (кратко)',
                   class: "form-control", autocomplete: "off", autofocus: true %>
</div>

<div class="mt-4 mb-2">
  <%= f.label "Подробное описание:" %>
</div>
<div>
  <%= f.text_area :body, required: true, minlength: 2, class: "form-control", rows: 5 %>
</div>

<% if @question.new_record? %>
  <div class="files">
    <p>Перетащите документ мышкой или нажимете <b><a href="#" type="file">здесь</a></b> чтобы прикрепить файл</p>
  </div>


  <div class="background-files">
    <%= f.file_field :question_files, multiple: true, class: "form-control" %>
  </div>
<% end %>

<div class="mt-4 mb-2">
  <%= f.label "Выберите исполнителя:" %>
</div>
<div>
  <%= f.collection_select :users_id, users, :id, :last_name %>
</div>

<%= f.submit "Создать", class: "w-100 btn btn-lg btn-primary", id: 'submit' %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_name, "Редактирование заявки" %>

<div class="main_form">
  <h1>Редактирование заявки</h1>

  <%= render 'form_create_question', users: @question_responsibles %>
</div>

app/views/questions/index.html.erb
<% provide :page_name, "Мои заявки" %>

<div class="mt-3 mb-5">
  <h1>Мои заявки</h1>
  <%= link_to image_tag("plus.svg"), new_question_path, id: 'plus' %>
</div>


<% @questions.each do |question| %>
  <% if question.statuses_id == 2 %>
    <article class="card mb-3" id="question-<%= question.id %>">
      <div class="card-body">

        <div class="responsible">
          <% creator_avatar = set_avatar question.user.id %>
          <% responsible_avatar = set_avatar question.users_id %>
          <div class="worked rotating" title="Заявка в работе"></div>
          <div>
            <%= image_tag("#{creator_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.user.id %></p>
          </div>

          <div>
            <%= image_tag("#{responsible_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.users_id %></p>
          </div>
        </div>

        <div class="card-info">
          <h3 class="mb-4 mt-0">
            <%= link_to "#{truncate question.title}", question_path(question), length: 50, class: 'link_title' %>
          </h3>
          <p>
            <%= truncate question.body, length: 80 %>
          </p>
        </div>
        <time>
          <% time = question.created_at.strftime('%d/%m %H:%M') %>
          <%= get_days time %>
        </time>
        <br>

        <div class="buttons">
          <%= link_to 'Открыть', question_path(question), class: 'btn btn-primary' %>
          <%= link_to 'Изменить', edit_question_path(question), class: 'btn btn-secondary text-white' %>
          <%= button_to 'Отменить', send_to_archive_question_path(question), class: 'btn btn-danger' %>
        </div>

      </div>

      <a href="#" class="arrow-down" id="get_all" value='0' onclick="get_all.value='1'">
        <i></i>
      </a>
    </article>
  <% elsif question.statuses_id == 3 %>
    <article class="card card-success card mb-3" id="question-<%= question.id %>">
      <div class="card-body">

        <div class="responsible">
          <% creator_avatar = set_avatar question.user.id %>
          <% responsible_avatar = set_avatar question.users_id %>
          <div>
            <%= image_tag("#{creator_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.user.id %></p>
          </div>

          <div>
            <%= image_tag("#{responsible_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.users_id %></p>
          </div>
        </div>

        <div class="card-info">
          <h3 class="mb-4 mt-0">
            <%= link_to "#{truncate question.title}", question_path(question), length: 50, class: 'link_title' %>
          </h3>
          <p>
            <%= truncate question.body, length: 80 %>
          </p>
        </div>
        <time>
          <% time = question.created_at.strftime('%d/%m %H:%M') %>
          <%= get_days time %>
        </time>
        <br>

        <div class="buttons">
          <%= link_to 'Открыть', question_path(question), class: 'btn btn-primary' %>
          <%= link_to 'Изменить', edit_question_path(question), class: 'btn btn-secondary text-white' %>
          <%= button_to 'Отменить', question_path(question), :method => :delete, class: 'btn btn-danger' %>
        </div>

      </div>

      <a href="#" class="arrow-down" id="get_all" value='0' onclick="get_all.value='1'">
        <i></i>
      </a>
    </article>
  <% else %>
    <article class="card mb-3" id="question-<%= question.id %>">
      <div class="card-body">

        <div class="responsible">
          <% creator_avatar = set_avatar question.user.id %>
          <% responsible_avatar = set_avatar question.users_id %>
          <div>
            <%= image_tag("#{creator_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.user.id %></p>
          </div>

          <div>
            <%= image_tag("#{responsible_avatar}") %>
            <p class="responsible_fio"><%= set_responsible_fio question.users_id %></p>
          </div>
        </div>

        <div class="card-info">
          <h3 class="mb-4 mt-0">
            <%= link_to "#{truncate question.title}", question_path(question), length: 50, class: 'link_title' %>
          </h3>
          <p>
            <%= truncate question.body, length: 80 %>
          </p>
        </div>
        <time>
          <% time = question.created_at.strftime('%d/%m %H:%M') %>
          <%= get_days time %>
        </time>
        <br>

        <div class="buttons">
          <%= link_to 'Открыть', question_path(question), class: 'btn btn-primary' %>
          <%= link_to 'Изменить', edit_question_path(question), class: 'btn btn-secondary text-white' %>
          <%= button_to 'Отменить', send_to_archive_question_url(question), class: 'btn btn-danger' %>
        </div>

      </div>

      <a href="#" class="arrow-down" id="get_all" value='0' onclick="get_all.value='1'">
        <i></i>
      </a>
    </article>
  <% end %>
<%end%>
<%= paginate @questions %> <!--if @questions.page(1).last_page?-->

<script type="text/javascript" charset="utf-8">
    var obj = document.getElementById("nav-2")
    obj.classList.toggle("nav_border")
</script>

app/views/questions/new.html.erb
<% provide :page_name, "Создание заявки" %>

<div class="main_form">
  <h1>Опишите задачу:</h1>

  <%= render 'form_create_question', users: @question_responsibles, projects: @collection_projects %>
</div>

<script type="text/javascript" charset="utf-8">
    var obj = document.getElementById("nav-3")
    obj.classList.toggle("nav_border")
</script>

<script type="text/javascript" charset="utf-8">
    document.addEventListener("turbolinks:load", function() {
        document.querySelectorAll('.js-multiple-select').forEach((element) => {
            let opts = {
                valueField: 'id',
                labelField: 'name',
                searchField: 'name',
                create: false,
                load: function(query, callback) {
                    const url = element.dataset.ajaxUrl + '.json?term=' + encodeURIComponent(query)

                    fetch(url)
                        .then(response => response.json())
                        .then (json => {
                            callback(json)
                        }).catch(() => {
                        callback()
                    })
                }
            }

            new TomSelect(element, opts)
        })
    })
</script>

app/views/questions/show.html.erb
<% provide :page_name, "#{@question.title}" %>
<% status = @question.statuses_id %>

<div class="responsible_show">

  <div>
    <% creator_avatar = set_avatar @question.user.id %>
    <% responsible_avatar = set_avatar @question.users_id %>
    <%= image_tag("#{creator_avatar}", title: "#{set_responsible_fio @question.user.id}") %>
    <%= image_tag("#{responsible_avatar}", title: "#{set_responsible_fio @question.users_id}") %>
  </div>

  <div class="buttons buttons-show">
    <% if status == 1 %>
      <%= button_to 'Взять в работу', start_working_question_path, class: 'btn btn-success text-white' %>
    <% elsif status == 2 %>
      <%= button_to 'Выполнить', completed_working_question_path, class: 'btn btn-success text-white' %>
    <% elsif status == 4 %>
      <%= button_to 'Сделать активной', back_to_active_question_path, class: 'btn btn-success text-white' %>
    <% else %>
      <%= button_to 'Вернуть в работу', start_working_question_path, class: 'btn btn-warning text-white' %>
    <% end %>

    <%= link_to 'Изменить', edit_question_path, class: 'btn btn-secondary text-white' %>

    <% if status == 4 %>
      <%= button_to 'Удалить', question_path(@question), :method => :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= button_to 'Отменить', send_to_archive_question_path, class: 'btn btn-danger' %>
    <% end %>
  </div>

</div>

<div class="view">
  <div class="go-back">
    <%= link_to image_tag("go_back.png"), _filtered_referrer %>
  </div>

  <div class="question-content">
    <div class="description">
      <h2 class="h2-view" id="h2-view"><%= @question.title %></h2>
      <p><%= @question.body %></p>
    </div>

    <% if @question.question_files.attached? %>
    <div class="files-container">
      <% @question.question_files.each do |t| %>
        <div class="files-content">
          <%= link_to rails_blob_path(t), target: :_blank do %>
            <%= image_tag "file_icon.png", class: 'file' %>
          <div>
            <%= t.filename %>
          </div>
          <div>
            <%= link_to 'Скачать', rails_blob_path(t, disposition: "attachment") %>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
<!--          <h1 id="point">{{count}}</h1>-->

    <div class="files">
      <p>Перетащите документ мышкой или нажимете <b><a href="#">здесь</a></b> чтобы прикрепить файл</p>
    </div>


    <div class="question-info">
      <% created_at = @question.created_at %>
      <% updated_at = @question.updated_at %>
      <% created_user = @question.user.id %>
      <div class="question-info-left">
        <p>
          <b>Создано:</b> <%= created_at.strftime("%d.%m.%y") %>
          <br>
          <b>Время:</b> <%= created_at.strftime("%H:%m") %> (часы/минуты)
          <br>
          <b>Создатель:</b> <%= set_responsible_fio created_user %>
        </p>
      </div>
      <div class="question-info-right">
        <p>
          <b>Обновлено:</b> <%= updated_at.strftime("%d.%m.%y") %>
          <br>
          <b>Время выполнения:</b> 4 часа
          <br>
          <b>Исполнитель:</b> <%= set_responsible_fio @question.users_id %>
        </p>
      </div>
    </div>
    <div class="question-end"></div>
    <div class="status">
      <h3>Статус заявки:
        <span>
          <%= set_status status %>
      </span>
      </h3>
    </div>
    <div class="question-end"></div>

      <p id="question-id">id: <%= @question.id %></p>
  </div>

  <div class="comment">
    <h2 class="h2-view" id="h2-chat">История общения:</h2>

    <% if @answers.blank? %>
      <%= render 'animation_empty_messages' %>
    <% end %>

    <div class="content-comment">
      <%= render partial: 'answers/answer', collection: @answers,
                 as: :answer, locals: {question: @question, current_user: current_user} %>
    </div>

    <%= render 'questions/form_create_answer' %>



  </div>
</div>