config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create destroy edit update]
  resources :projects, only: %i[new create destroy edit update]
  resources :archives

  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end

  root 'pages#index'
  get 'session' => 'sessions#destroy'

  resources :questions do
    post :start_working, on: :member
    post :completed_working, on: :member
    post :send_to_archive, on: :member
    post :back_to_active, on: :member
    get :back_to_active, on: :member
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question, optional: true
  belongs_to :user, optional: true

  validates :body, presence: true, length: {minimum: 2}
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :set_question!
  before_action :my_message?, only: %i[edit update destroy]

  def create
    @answer = @question.answers.build answer_create_params

    if @answer.save
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order created_at: :desc
      render 'questions/show'
    end
  end

  def show; end

  def edit
    @answer = @question.answers.find params[:id]
  end

  def update
    answer = @question.answers.find params[:id]
    if answer.update answer_update_params
      flash[:check] = 'Сообщение изменено!'
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    answer = @question.answers.find params[:id]
    answer.destroy
    flash[:times] = 'Сообщение удалено!'
    redirect_to question_path(@question)
  end

  private

  def my_message?
    answer = @question.answers.find params[:id]
    return if answer.user.id == current_user.id

    flash[:times] = "Вы не можете редактировать чужое сообщение!"
    redirect_to questions_path
  end

  def answer_create_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

end

app/views/answers/_answer.html.erb
<% if answer.user.id == current_user.id %>
  <div class="my_message">
    <div class="message-buttons">
      <%= link_to 'Изменить', edit_question_answer_path(question, answer), class: 'buttons_message' %>
      <%= button_to 'Удалить', question_answer_path(question, answer), class: 'buttons_message', :method => :delete %>
    </div>

    <div>
      <p><%= answer.body %></p>
    </div>
  </div>
<% else %>
  <div class="message">
    <div>
      <h6><%= set_responsible_fio answer.user.id %></h6>
      <p><%= answer.body %></p>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_name, "Редактировать сообщение" %>

<div class="main_form">
  <h1>Редактировать сообщение</h1>

  <%= render 'questions/form_create_answer' %>
</div>