config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create destroy edit update]
  resources :projects, only: %i[new create destroy edit update]
  resources :archives

  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end

  root 'pages#index'
  get 'session' => 'sessions#destroy'

  resources :questions do
    post :start_working, on: :member
    post :completed_working, on: :member
    post :send_to_archive, on: :member
    post :back_to_active, on: :member
    get :back_to_active, on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title><%= title_name(yield(:page_name)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "edit_profile", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "fade_effect", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "message_alert", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "animation_empty_messages", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "clock", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="clock">
      <div class="wrap">
        <span class="hour"></span>
        <span class="minute"></span>
        <span class="second"></span>
        <span class="dot"></span>
      </div>
    </div>

    <div class="date-now">
      <h4><%= Time.new.day %></h4>
      <p><%= days_weeks %></p>
    </div>

  <header class=" container d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <h1 id="logo"><b>S - <span id="logo-span">team</span></b></h1>
    </a>

    <ul class= "nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li id="nav-1"><%= link_to 'Главная', root_path, class: 'nav-link px-2 link-secondary fw-bold' %></li>
      <li id="nav-2"><%= link_to 'Мои заявки', questions_path, class: 'nav-link px-2 link-secondary fw-bold ' %></li>
      <li id="nav-3"><%= link_to 'Создать заявку',new_question_path, class: 'nav-link px-2 link-secondary fw-bold' %></li>
    </ul>

    <div class="col-md-3 text-end">
      <% if user_signed_in? %>
        <p class="dropdown" data-toggle="dropdown">
          <% fio = set_responsible_fio current_user.id %>
          <%= link_to fio, "#", class: 'nav-link px-2 dropdown-toggle', data: {"bs-toggle": 'dropdown'} %>
          <%= image_tag "#{set_avatar(current_user)}", class: "my_avatar" %>
        </p>

        <ul class="dropdown-menu" id="dropdown-menu">
          <li><%= link_to 'Профиль', edit_user_path(current_user), class: "dropdown-item" %></li>
          <li><%= link_to 'Архив', archives_path, class: "dropdown-item" %></li>
          <li><%= link_to 'Новый проект', new_project_path, class: "dropdown-item" %></li>
          <div class="dropdown-divider"></div>
          <li><%= link_to 'Выход', session_path, class: "dropdown-item btn-danger text-white",
                         id: "exit", :method => :delete %></li>
        </ul>

      <% else %>
        <%= link_to 'Войти', new_session_path, class: 'btn btn-secondary me-2 text-white' %>
        <%= link_to 'Зарегистрироваться', new_user_path, class: 'btn btn-primary' %>
      <% end %>
    </div>

  </header>

  <div class="main">
    <main class="mt-3">

      <% unless flash.empty? %>
        <% flash.each do |k, v|%>
          <div class="fade-in flash Message Message--<%= k %>" id="get_close">
            <div class="Message-icon">
                <i class="fa fa-<%= k %>"></i>
            </div>

            <div class="Message-body">
              <%= tag.div v, role: 'alert' %>
            </div>

            <button onclick="(document.getElementById('get_close').style.display='none')"
                    type="button" class="Message-close">
              <i class="fa fa-times"></i>
            </button>
        </div>
        <% end %>
      <% end %>



        <%= yield %>

      <% if flash.present? %>
        <script type="text/javascript" charset="utf-8">
          var fade_effects = document.getElementById("get_close")

          setTimeout(() => {fade_effects.classList.remove("fade-in")}, 2000);
          setTimeout(() => {fade_effects.classList.toggle("fade-out")}, 4000);
          setTimeout(() => {fade_effects.style.display='none'}, 5500);
        </script>
      <% end %>

        <script type="text/javascript" charset="utf-8">
            var inc = 1000;

            clock();

            function clock() {
                const date = new Date();

                const hours = ((date.getHours() + 11) % 12 + 1);
                const minutes = date.getMinutes();
                const seconds = date.getSeconds();

                const hour = hours * 30;
                const minute = minutes * 6;
                const second = seconds * 6;

                document.querySelector('.hour').style.transform = `rotate(${hour}deg)`
                document.querySelector('.minute').style.transform = `rotate(${minute}deg)`
                document.querySelector('.second').style.transform = `rotate(${second}deg)`
            }

            setInterval(clock, inc);

        </script>

      </main>
    </div>
  </body>
</html>